[package]
name = "rs-cryptopals"
version = "0.1.0"
authors = ["Henry Post <HenryFBP@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
substring = "1.4.0"
